theme: jekyll-theme-architect
title: Who is this house for?
describtion: This house is designed for people that want to help the earth. The house is specifically designed to be as eco friendly as possible. By adding a few differences depending on where you live this will be the perfect house for you.
