===== CUSTOMIZABLE COLORS AND IMAGES =====
*/
:root { 
	--main-color: #007dbd;
  --hover-color: #03679b;
  --background-image: url(https://s-media-cache-ak0.pinimg.com/originals/60/c4/bb/60c4bb55215c989b15b0fe144c73cf82.jpg);
  --popup-background: url(https://s-media-cache-ak0.pinimg.com/originals/60/c4/bb/60c4bb55215c989b15b0fe144c73cf82.jpg);
 }


/*
description: let's see if this works now
